### ISSUE TITLE
 ha-mercury-200-интеграция

### ISSUE THREAD

**Issue by AndreyPetrovich** [MenshikovDmitry/ha-mercury-200-integration#1]
Доброе время суток Дмитрий.  Нашел вашу интеграцию в интернете.   Скачал через hacs, но установить не получается. Подскажите как это сделать. Я новичок в программировании и home assistant. Заранее благодарен.

**Comment by MenshikovDmitry** [comment]
Добрый день!
Боюсь, без передающего модема интеграция не принесет пользы. 
Сначал необходимо установить интеграцию через HACS (рекомендую обратиться к документации самого HACS)
Затем, чтобы устройство появилось в сущностях, необходимо добавить соответствующую запись в configuration.yaml (см описание в репозитории) и перезагрузить HA.

**Comment by AndreyPetrovich** [comment]
Добрый день. Да я это прекрасно понимаю и сделал.
 И обязательно планирую собрать zigbee modem. Проблема в том, что ссылки на вашей странице в github нет. Скачал по ссылке https://github.com/MenshikovDmitry/ha-mercury-200-integration.  Захожу в настройки - интеграции - добавить интеграцию, а там интеграции нет. Даже прописал configuration.yaml. Подскажите пожалуйста почему. Спасибо.
![Снимок экрана 2022-10-02 200834](https://user-images.githubusercontent.com/73443427/193466981-f14ff756-3021-466c-b5ef-27abfa602b0d.png)
![Снимок экрана 2022-10-02 200937](https://user-images.githubusercontent.com/73443427/193466983-346d70ab-98b8-499e-bc09-664f21c26407.png)

**Comment by MenshikovDmitry** [comment]
Моей интеграции в HACS нет. Чтобы установить, нужно сначала добавить репозиторий (три точки нажать) Скачивать ничего не нужно. После этого ее можно будет найти в интеграциях в HACS. 
Документация тут: https://hacs.xyz/docs/faq/custom_repositories/ 
Видео: https://www.youtube.com/watch?v=xpqUe-TkO70

**Comment by AndreyPetrovich** [comment]
Доброе время суток.  Я все это сделал. Не первую интеграцию устанавливаю из репозитория. Если посмотрите на первое фото то видно, что она скачалась из репозитория. После этого она должна появиться в списке интеграция в меню настройки для дальнейшей инсталляции в НА. А ее там нет.  Фото 2.  Я не могу ее инсталлировать в HA. В этом и есть мой вопрос.  Скачивал по этой ссылке:  https://github.com/MenshikovDmitry/ha-mercury-200-integration.  Искал в интеграциях по ключевому слову " mercury" и "меркурий".  В чем моя ошибка ???
Спасибо.

**Comment by MenshikovDmitry** [comment]
После установки интеграция появляется в _настройки-интеграции_ только в том случае, если разработчик для нее "интерфейс", что верно далеко не для всех интеграций. 
В репе написано, что после установки и перезагрузки необходимо добавить в configuration.yaml:

```
# Electricity Counter Mercury200.02
mercury200:
  - type: mercury200.02
    device_serial: "XXXXXXXX" 
    topic: "zigbee2mqtt/rs485"
```
После перезагрузки Вы увидите сущности, относящиеся к Вашему счетчику. 
Поймите меня правильно, я сейчас Вас консультирую не по работе и настройке своего компонента, а по работе Home Assistant в целом, что не совсем правильно. 
Я бы рекомендовал начать с чего-то попроще: Лампочки, температура, увлажнители, пылесосы, счетчики для воды от ModCam, базовые автоматизации и тп. 

С Вашего позволения, закрываю issue.

**Comment by MenshikovDmitry** [comment]
После установки интеграция появляется в _настройки-интеграции_ только в том случае, если разработчик для нее "интерфейс", что верно далеко не для всех интеграций. 
В репе написано, что после установки и перезагрузки необходимо добавить в configuration.yaml:

```
# Electricity Counter Mercury200.02
mercury200:
  - type: mercury200.02
    device_serial: "XXXXXXXX" 
    topic: "zigbee2mqtt/rs485"
```
После перезагрузки Вы увидите сущности, относящиеся к Вашему счетчику. 
Поймите меня правильно, я сейчас Вас консультирую не по работе и настройке своего компонента, а по работе Home Assistant в целом, что не совсем правильно. 
Я бы рекомендовал начать с чего-то попроще: Лампочки, температура, увлажнители, пылесосы, счетчики для воды от ModCam, базовые автоматизации и тп. 

С Вашего позволения, закрываю issue.
