### ISSUE TITLE
Не показывает данные счетчика

### ISSUE THREAD

**Issue by AndreyPetrovich** [MenshikovDmitry/ha-mercury-200-integration#2]
Доброе время суток Дмитрий.
Собрал и прошил модем.  К z2mqtt подключился но выдает ошибки (фото ошибка 1 и 2).  Синий светодиод на модеме мигает раз в 5 секунд. В НА появились сущности напряжения, Т1, Т2,Т3, Т4 и мощность (фото). Но помимо них появились еще 34 сущности (фото). Так и должно ??? Но данные со счетчика не приходят. Все соединения и питание проверил. Прошивка прошла без проблем. 
Подскажите пожалуйста, что делать. Уже убил 2 дня, но ничего не могу сделать. Я не сильно понимаю во всем этом. Это мое хобби и знаний еще не хватает. 
С огромным уважение к вам и большое спасибо за данный проект.
Андрей.
![автоматизации](https://user-images.githubusercontent.com/73443427/205100625-73120635-f9dd-463c-a726-24f5a8c0c43f.png)
![Запись в configuration yaml](https://user-images.githubusercontent.com/73443427/205100629-9019e5c4-ce44-4bdf-947f-5877f80a6499.png)
![Снимок экрана 2022-12-01 182113](https://user-images.githubusercontent.com/73443427/205100632-b0ef9f87-b57e-413c-87a9-65b1e96ab069.png)
![Снимок экрана 2022-12-01 183546](https://user-images.githubusercontent.com/73443427/205100635-af699e23-c1ce-4294-a5d4-8aea34c38311.png)
![Снимок экрана дополнительных сущностей 1](https://user-images.githubusercontent.com/73443427/205100638-f0bb7c56-de11-4c5c-8acd-a19186ae4505.png)
![Снимок экрана дополнительных сущностей 2](https://user-images.githubusercontent.com/73443427/205100642-e0178514-0ca7-4b32-b424-2764dd906302.png)
![Снимок экрана дополнительных сущностей](https://user-images.githubusercontent.com/73443427/205100644-e9e953c1-fd21-420d-a5f5-6dcd0f569f71.png)

**Comment by AndreyPetrovich** [comment]
![ошибка  1 z2mqtt](https://user-images.githubusercontent.com/73443427/205101358-728d47f9-77b0-496d-a187-97f3459dbd80.jpg)
![ошибка  2 z2mqtt](https://user-images.githubusercontent.com/73443427/205101366-ac6eadf5-d439-4ace-aac1-a8964d994040.jpg)

**Comment by MenshikovDmitry** [comment]
Добрый день! Спасибо за сообщение, давайте разбираться :)
Самое первое что стоит проверить, что Вы переименовали модем в  ZigBee2MQTT. При подключении устройствам присваивается имя по умолчанию (это mac-адрес устройства), Вам необходимо переименовать его в rs485 (как вы указали в конфиге). Если Все собрано и прошито верно, то проблема скорее всего именно тут.

Далее.
Да, при установке интеграции у Вас появятся сущности, относящиеся к Вашему электросчетчику (Т1-Т4 + мощность и напряжение). А при подключении модема к Zigbee2MQTT - он тоже притаскивает целую пачку дефолтных сущностей. Это связано с тем, что используется дефолтная конфигурация прошивки PTVO. Чтобы этих лишних сущностей не появлялось, необходимо сделать внешний конвертер. Я, признаться, этим не занимался и не подскажу как это сделать. Если у Вас дойдут руки, пожалуйста, дайте знать, обновим репу :)

Далее. Диагностика.
Как я писал в репе, модем просто перекидывает пакеты между MQTT  и RS485. Таким образом нужно понять где они теряются. 
1) Залезаем в MQTT (интеграции - MQTT, либо любым другим внешним MQTT клиентом)  и слушаем что происходит в топике модема, как Вы указали в конфиге (zigbee2mqtt/rs485/#)
2) Если коротко нажать на модеме единственную кнопку, Вы должны увидеть в топике статус. Если нажание кнопки не видно в MQTT, значит модем не в сети - можно попробывать переспарить устройство, либо проблема сборки модема (плохой контакт).
3) запускаем сервис получения информации  от счетчика. Это можно сделать, например, через кнопку в карточке Lovelace. Либо дождаться пока автоматизация сделает это. Опять же. Вы должны видеть запрос в топике. 
4) На плате TTL <-> RS485 находятся два светодиода - TXD и RXD. В момент получения команды из MQTT один из них моргнет - значит он передает пакет из MQTT в RS485 (на счетчик).
5) По-хорошему, если все подключено верно, буквально в то же мгновение должен моргнуть и второй счетодиод. Это значит что счетчик получил пакет и сразу на него ответил, после чего модем прокидывает ответ от счетчика в MQTT в Ваш топик. Где Вы и должны его увидеть)
6) получив сообщение в нужный топик, интеграция должна расшифровать его и обновить значения сущностей.

Посмотрите, на каком этапе теряется сообщение, будем думать дальше.

**Comment by AndreyPetrovich** [comment]
Большое спасибо Дмитрий.
Насколько понимаю изменить имя надо здесь: 
![Снимок экрана 2022-12-04 064852](https://user-images.githubusercontent.com/73443427/205473421-4083e023-5964-4f23-8ebe-f282db40cec5.png)
Обратил внимание, что светодиоды на модеме не мигают при передачи команды. Буду разбираться с модемом. И подскажите пожалуйста надо что то менять в этом файле: 
![Снимок экрана 2022-12-04 065038](https://user-images.githubusercontent.com/73443427/205473490-f50fa42d-99da-478c-96bf-827980cb7a43.png)
Еще раз большое спасибо.

**Comment by AndreyPetrovich** [comment]
И вот что пишет в логе z2mqtt:
![Снимок экрана 2022-12-04 065726](https://user-images.githubusercontent.com/73443427/205473618-1e92ccff-6048-4242-be4a-b4490290892a.png)

**Comment by AndreyPetrovich** [comment]
Видно, что отправляется команда, а ответа нет:
![Снимок экрана 2022-12-04 070016](https://user-images.githubusercontent.com/73443427/205473710-6a3de864-e1bc-49be-bca0-7076b5b7483a.png)
И подскажите пожалуйста в настройках счетчика надо что-то менять. В инструкции ничего не нашёл, но вдруг ...

**Comment by MenshikovDmitry** [comment]
По скриншоту не понятно где Вы.
Модем нужно переименовать в интерфейсе zigbee2mqtt. Нужно установить для него friendly_name.
 Должно быть так:
![Screenshot_20221204-194025](https://user-images.githubusercontent.com/26637464/205484103-9e115dc4-87b1-4b50-bbf1-b38a6d511b57.png)
![Screenshot_20221204-193755](https://user-images.githubusercontent.com/26637464/205484116-62de2ecb-de1f-4395-925d-1b20718d259c.png).

В файлы проекта лазить не нужно.

Видно что команда поступает в топик. Но не видно чтобы в этот топик приходил статус от модема (см п 2)

Могу ошибаться, но пока что на лицо что Вы не переименовали устройство в z2m

**Comment by MenshikovDmitry** [comment]
По скриншоту не понятно где Вы.
Модем нужно переименовать в интерфейсе zigbee2mqtt. Нужно установить для него friendly_name.
 Должно быть так:
![Screenshot_20221204-193755~2](https://user-images.githubusercontent.com/26637464/205484394-b9d35e8e-0167-444b-b4d2-62c19e2720bf.png)
![Screenshot_20221204-194025~2](https://user-images.githubusercontent.com/26637464/205484398-0294c16d-feaa-41d2-aca5-a63bd2457766.png)


В файлы проекта лазить не нужно. Счётчик также у всех заработал без изменений.

Видно что команда поступает в топик. Но не видно чтобы в этот топик приходил статус от модема (см п 2)

Могу ошибаться, но пока что на лицо что Вы не переименовали устройство в z2m

**Comment by AndreyPetrovich** [comment]
Да, вы оказались правы Дмитрий. 
Еще раз огромное  вам спасибо за уделенное время и за данный проект.

**Comment by MenshikovDmitry** [comment]
Так все заработало? :-). Если так, то я очень рад.
Закрываем issue?
