### ISSUE TITLE
Поддержка счетчика Меркурий 206

### ISSUE THREAD

**Issue by DaN66O** [MenshikovDmitry/ha-mercury-200-integration#3]
Добрый день.
Ваша интеграция будет поддерживать данный счетчик без адаптации ?
Или надо будет что то переделывать ?

**Comment by MenshikovDmitry** [comment]
Добрый день!
Как я понял, в линейке 206 несколько разных счетчиков с разными особенностями

Если Ваш счетчик имеет разъем RS485, то, как минимум, модем не нуждается в переделке и может пробрасывать команды со счетчика в MQTT и обратно.

Как написано в документации, формирование и расшифровку команд выполняет интеграция (код на питоне). Если протокол различается с Меркурий200, то понадобится доработка интеграции (Нужно будет добавить поддержку нового устройства). Я готов проявить содействие, но саму доработку (формирование и расшифровка байт-строк) Вам придется делать самому. У меня сейчас под рукой нет ни Меркурия, ни умного дома.
