### ISSUE TITLE
перестала работать после обновления НА до 2023.3

### ISSUE THREAD

**Issue by AndreyPetrovich** [MenshikovDmitry/ha-mercury-200-integration#4]
Добрый день Дмитрий. Большое спасибо за вашу интеграцию. 
После обновления НА до версии 2023.3 вчера интеграция перестала работать. Поискав причину наткнулся вот на это:
https://www.home-assistant.io/blog/2023/03/01/release-20233/#breaking-changes
https://developers.home-assistant.io/blog/2023/02/21/deprecated-callback-removed
Не подскажите какие и где надо внести изменения для возобновления работы интеграции.
Заранее благодарен.
С уважением, Андрей.

**Comment by MenshikovDmitry** [comment]
Андрей, здравствуйте!
Спасибо за комментарий и за ресурсы. 
Да, действиетльно в новом релизе они изменили метод подписки на топики MQTT, который я и использую. К сожалению, у меня нет под рукой умного дома, но если Вы сможете отладить у себя, это бы очень помогло. Я готов оказать содействие. Потом - выпустим релиз, чтобы у всех остальных тоже все заработало.

Итак. На сколько я понимаю, необходимо переехать на новую схему подписки на топик:
custom_components - mercury200 - init - строчка 99.
Как указано в ресурсе, которым Вы поделились (https://developers.home-assistant.io/blog/2023/02/21/deprecated-callback-removed),  они "упаковали" topic, payload и qos в единый объект класса RecieveMessage. На сколько я понимаю, нужно заменить:

`@callback` 
` async def message_received(topic: str, payload: str, qos: int) -> None:`
на
`@callback`
`def message_received(msg: ReceiveMessage) -> None:`
`  topic = msg.topic   `
`  payload = msg.payload  `
`  qos = msg.qos  `

То есть принимать на вход только один объект класса ReceiveMessage и "распаковывать" его.
+ соответственно, нужно импортировать ReceiveMessage в начале init (где все остальные импорты). 
Что-то типа:
`
from homeassistant.components.mqtt.select import ReceiveMessage
`

Опять же, тут могут содержаться неточности, т.к., к сожалению, не могу ничего проверить самостоятельно. Могу только читать код и делать предположения.

Дайте знать как будет продвигаться дело!

**Comment by tuzovvlad** [comment]
Доброго дня! Правки внес, вроде все работает. Пока тестирую, наблюдаю. Позже отпишусь.

**Comment by AndreyPetrovich** [comment]
Доброе утро Владимир. Внес изменения но не работает. Подскажите что изменили и где. 
Заранее благодарен.
С уважением, Андрей.

**Comment by tuzovvlad** [comment]
Как и написал Дмитрий. 
Заменил:
    @callback
     async def message_received(topic: str, payload: str, qos: int) -> None:
На
    @callback
    def message_received(msg: ReceiveMessage) -> None:
        topic = msg.topic
        payload = msg.payload
        qos = msg.qos
И вначале вставил:
from homeassistant.components.mqtt.select import ReceiveMessage
Там где остальные импорты и вызовы. Получилось так:
from homeassistant.components import mqtt
from homeassistant.components.mqtt.select import ReceiveMessage
from homeassistant.core import HomeAssistant, ServiceCall, callback
from homeassistant.helpers.typing import ConfigType

**Comment by tuzovvlad** [comment]
Скидываю свой файл init для ознакомления. Он может отличаться от Вашего, так как я мог внести в него свои правки ранее.

**Comment by tuzovvlad** [comment]
[__init__.txt](https://github.com/MenshikovDmitry/ha-mercury-200-integration/files/10880158/__init__.txt)

**Comment by AndreyPetrovich** [comment]
Спасибо. Уже нашел ошибку. Огромное спасибо.

**Comment by MenshikovDmitry** [comment]
@VladimirTuzovGitHub,  @AndreyPetrovich, Как полет? Нормальный?

Если да, собиру релиз тогда на неделе.

**Comment by AndreyPetrovich** [comment]
Да Дмитрий все отлично.Обновилс до 2023.3.1. Полет нормальный.

вт, 7 мар. 2023 г., 06:30 Dmitry Menshikov ***@***.***>:

**Comment by tuzovvlad** [comment]
У меня тоже все работает, как было до обновления.
Найти бы еще кто смог бы написать прошивку, чтобы не было предупреждений в журнале НА.

**Comment by MenshikovDmitry** [comment]
@VladimirTuzovGitHub , Владимир, обратил внимание, что В Вашем файле Вы изменили 200.02 на 200.04.
Правильно понимаю, что интеграция также работает для 200.04? Могу добавить 200.04 в список поддердживаемых устройств? Или Вы доработали ее? Если да, сможете поделиться кодом?

Спасибо!

**Comment by tuzovvlad** [comment]
Дмитрий приветствую! Да, с 200.04 тоже работает с Вашим кодом. Но есть некоторые моменты на которые я вносил изменения в код, связанные с добавлением сенсора Сила тока Current. Какие еще уже не помню, прикреплю архив с моим кодом для анализа.
[mercury200.zip](https://github.com/MenshikovDmitry/ha-mercury-200-integration/files/10963682/mercury200.zip)

**Comment by MenshikovDmitry** [comment]
Всем спасибо, выкатил релиз с фиксом.
Добавил "официальную" поддержку Меркурий 200.04
Добавил Сенсор на силу тока.

Закрываем issue
