### ISSUE TITLE
Подключение к счетчику

### ISSUE THREAD

**Issue by Semenov-Alexander** [MenshikovDmitry/ha-mercury-200-integration#6]
Здравствуйте Дмитрий, как Вы считаете возможно ли подключение к счетчику если туда уже подключена управляющая компания? Открыл счетчик, а там уже есть подключенные 4 провода :( Полагаю, что о параллельном подключении и речи нет, чей ответ будем ловить с порта тогда не понятно... любые идеи пожалуйста.

**Comment by MenshikovDmitry** [comment]
Александр, здравствуйте!
Спаибо за интерес к проекту :).

Я таких экспериментов не проводил, но, по логике вещей, Вы можете подключиться к имеющейся RS-485 шине, которую подключила управляющая компания.

Если все заработает как я предполагаю, то в z2m топике модема Вы сможете слушать все что происходит на шине, а это опрос всех устройств, которые к ней подключены и, соответственно, ответы.
Компонент будет пытаться  расшифровать все сообщения, и, увидив серийник Вашего счетчика, обновит значения сенсоров в ХА. На все нерелевантные сообщения он будет гадить в ЛОГ файл 
![image](https://github.com/MenshikovDmitry/ha-mercury-200-integration/assets/26637464/15fa401b-cf98-43f8-bec5-a492c7c460f1)
Вы можете смело закомментить ненужные сообщения.

По идее, с помощью модема Вам ничего не мешает также опрашивать свой счетчик, но тогда эти сообщения будут видны и всем устройствам на шине, в том числе и управляющей компании (если они будут как-то мониторить "посторонние" сообщения).

Также не стоит забывать что В случае, если Вы будете опрашивать Ваш счетчик одновременно с тем как управляющая компания будет опрашивать другие устройства, Сообщения потенциально могут вступить в конфликт. И ответа не получите ни Вы, ни они.

Еще раз, это всего лишь мои домыслы, так как я не являюсь экспертом в слаботочных сетях.

**Comment by Semenov-Alexander** [comment]
Мое почтение! Благодарю за ответ. По той [спецификации RS-485](https://owen.ru/forum/attachment/8/8/3/9/10880.attach), которая мне попадалась, нельзя "звездой" подключаться к "мастеру". Значит остается только либо импульсы считать с лампочки счетчика, либо ставить свой второй счетчик после штатного... Видел сейчас есть счетчики Меркурий уже с Zibbee .... вопрос только интеграции их в HA и стоимости как чугунный мост :))))

**Comment by MenshikovDmitry** [comment]
Я бы все равно попробывал :). По идее слушать Вам точно никто не помешает
(но это не точно)))
