### ISSUE TITLE
Ошибки в ядре homeassistant

### ISSUE THREAD

**Issue by AndreyPetrovich** [MenshikovDmitry/ha-mercury-200-integration#7]
Доброго времени суток Дмитрий. 
Еще раз благодарю вас за эту замечательную интеграцию. После последних обновлений ядра home assistant стали всплывать такая ошибка и четыре предупреждения.
Подскажите пожалуйста где и что надо исправить в интеграции. Насколько понимаю предупреждение связано с тем, что вместо запятых надо ставить - или _ , но где это исправить не знаю. 
Заранее Вам благодарен за ответ.
С уважением, Андрей.

2023-11-08 22:00:00.195 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'zigbee2mqtt/electricity_counter': '{"action":null,"last_seen":"2023-11-08T19:00:00.182Z","linkquality":120}'
Traceback (most recent call last):
  File "/config/custom_components/mercury200/__init__.py", line 112, in message_received
    if len(response) == 0:
       ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

2023-11-08 22:00:00.545 WARNING (MainThread) [homeassistant.components.mqtt.discovery] 
Received message on illegal discovery topic 'homeassistant/device_automation/0x00124b002accb7e6/action_0,15,41,9,99,34,137,1,149,0,4,2,39,104,0,15,41,9,39,1,34,66,9,0,50,9,147,0,0,0,0,0,0,0,0,195,185/config'. 
The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic
2023-11-08 22:00:00.549 WARNING (MainThread) [homeassistant.components.mqtt.discovery] 
Received message on illegal discovery topic 'homeassistant/device_automation/0x00124b002accb7e6/action_0,15,41,9,99,34,137,1,149,0,4,2,39,104,0,15,41,9,39,1,34,66,9,0,50,9,147,0,0,0,0,0,0,0,0,195,185/config'. 
The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic
2023-11-08 22:00:00.551 WARNING (MainThread) [homeassistant.components.mqtt.discovery] 
Received message on illegal discovery topic 'homeassistant/device_automation/0x00124b002accb7e6/action_0,15,41,9,99,34,137,1,149,0,4,2,39,104,0,15,41,9,39,1,34,66,9,0,50,9,147,0,0,0,0,0,0,0,0,195,185/config'. 
The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt/#discovery-topic
2023-11-08 22:00:00.552 WARNING (MainThread) [homeassistant.components.automation.puge_retain_mqtt_messages] puge retain MQTT messages: Already running

**Comment by MenshikovDmitry** [comment]
Андрей, здравствуйте!

Спасибо на добром слове :).

Странная ошибка, вроде я ее уже фиксил, ну да ладно, поставил еще одну заглушку. Посмотрите строчки 112 и 113 в __init__.py:
```python
        if response is None:
            return  
```
Я сделал комит, попробуйте обновить компонент через HACS ну или прям в коде у себя. Я, к сожалению, не имею на руках свежего ХА со счетчиком и не могу протестировать, увы. Напишите получилось ли избавиться от ошибки.

Что до Ворнингов, тут, боюсь, не смогу помочь. Сообщения гоняются через серийный порт, все они уникальны и ХА всегда будет пытаться "скогфигурировать устройство" и, соответственно, ругаться на неверный discovery topic. Можно только дропать эти сообщения (Как я вижу, это Вы и так делаете). Я не знаю как отключить обнаружение в этом топике и не уверен что это возможно. Быть может, нужно сделать кастомный z2m конвертер... Если найдете решение, дайте знать, допилю :)

**Comment by AndreyPetrovich** [comment]
Доброго времени суток Дмитрий.
Большое спасибо за помощь. Ошибка пропала.
С наилучшими пожеланиями, Андрей.
