### ISSUE TITLE
Сссылки для заказа компонетов платы устарели

### ISSUE THREAD

**Issue by gdbd** [MenshikovDmitry/ha-mercury-200-integration#8]
Добрый день!
На странице https://github.com/MenshikovDmitry/ha-mercury-200-integration/tree/master/ZigBee2MQTT%20%3C-%3E%20RS485
многие ссылки на компоненты для заказа с АЭ не работают

**Comment by MenshikovDmitry** [comment]
Спасибо за интерес к проекту. Увы, ссылки на АЭ имеют тенденцию устаревать.
Буду рад Вашему Pull Request
